name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  npm_security_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code 
      uses: actions/checkout@v4
    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependences
      run: npm install
    - name: Execute tests 
      run: npm run test
      
  integration_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code 
      uses: actions/checkout@v4
    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependences
      run: npm install
    - name: Run Integration tests 
      run: npm run test
