name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code 
      uses: actions/checkout@v4
    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install npm dependences
      run: npm install
    - name: Install Playwright 
      run: npx playwright install  
    - name: Start the backend 
      run: npm run start-be &
    - name: Start the frontend 
      run: npm run start-fe &
    - name: Start UI tests
      run: npm run test:ui

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build_and_test  
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Deploy frontend
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.BACKEND_API_KEY }}
          api_key: ${{ secrets.RENDER_KEY }}
          clear_cache: true
          wait_deploy: true
          github_token: ${{ secrets.TOKEN_GH }}

  deploy-frontend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: deploy-backend
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Deploy backend
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.FRONTEND_API_KEY }}
          api_key: ${{ secrets.RENDER_KEY }}
          clear_cache: true
          wait_deploy: true
          github_token: ${{ secrets.TOKEN_GH }}